force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time_Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Log__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Log__c/fields/Project_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Project_Assignment__c</fullName>
    <label>Project Assignment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project_Assignment__c.User__r.Id</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Assignment__c</referenceTo>
    <relationshipLabel>Time_Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectSummaryTest.cls
@isTest
public class ProjectSummaryTest {
    @TestSetup
    static void setupTestData()
    {

        Project__c project = new Project__c(Name = 'Project 1', Status__c = 'In Progress');
        insert project;

        Project_Assignment__c projectAssignment = new Project_Assignment__c(Project__c = project.Id, User__c = UserInfo.getUserId()); 
        insert projectAssignment;
        
        List<Time_Log__c> timeLogs = new List<Time_Log__c>();
        
        timeLogs.add(new Time_Log__c(
            Name = 'feature: make some changes on main page', 
            Project_Assignment__c = projectAssignment.Id,
            Duration__c = 4
        ));
        timeLogs.add(new Time_Log__c(
            Name = 'bug: fixed syntax bug in TimeLogManager class', 
            Project_Assignment__c = projectAssignment.Id,
            Duration__c = 2
        ));
        timeLogs.add(new Time_Log__c(
            Name = 'feature: add new button', 
            Project_Assignment__c = projectAssignment.Id,
            Duration__c = 7
        ));
        
        insert timeLogs;
    }
    @isTest
    static void projectSummaryConstructorTest()
    {
        List<Project__c> project = [SELECT Id, Name From Project__c Limit 1];
        ProjectSummary projectSummary = new ProjectSummary(project[0]);

        System.assertEquals('Project 1', projectSummary.projectName);
    }
}