force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time_Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Log__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Log__c/fields/Project_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Project_Assignment__c</fullName>
    <label>Project Assignment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project_Assignment__c.User__r.Id</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Assignment__c</referenceTo>
    <relationshipLabel>Time_Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TimeLogManager.cls
public class TimeLogManager {
    
    public Map<Id, List<Time_Log__c>> groupByProject(List<Time_Log__c> logs) {
        Map<Id, List<Time_Log__c>> groupedLogs = new Map<Id, List<Time_Log__c>>();
        
        for (Time_Log__c log : logs) {
            if (log.Project_Assignment__r?.Project__c == null) {
                throw new IllegalArgumentException('Exception: field Project_Assignment__r is not loaded');
            }
            
            Id projectId = log.Project_Assignment__r.Project__c;
            
            if (groupedLogs.containsKey(projectId)) {
                groupedLogs.get(projectId).add(log);
            } else {
                List<Time_Log__c> projectLogs = new List<Time_Log__c>();
                projectLogs.add(log);
                groupedLogs.put(projectId, projectLogs);
            }
        }
        return groupedLogs;
    }
    
    public void processRecords(List<sObject> records) {
        for (sObject record : records) {
            if (record instanceof Project__c) {
                Project__c project = (Project__c) record;
                System.debug('Name: ' + project.Name + ', Status__c: ' + project.Status__c);
            } else if (record instanceof Time_Log__c) {
                Time_Log__c log = (Time_Log__c) record;
                System.debug('Name: ' + log.Name + ', Date__c: ' + log.Date__c + ', Hours__c: ' + log.Duration__c);
            }
        }
    }
    
    public List<Time_Log__c> searchLogs(Map<String, Object> filters) {
        String query = 'SELECT Id, Name, Date__c, Description__c ' +
                       'FROM Time_Log__c';
        
        List<String> conditions = new List<String>();
        
        for (String key : filters.keySet()) {
            Object value = filters.get(key);
            
            switch on key {
                when 'ProjectId' {
                    String projectId = String.escapeSingleQuotes(String.valueOf(value));
                    conditions.add('Project_Assignment__r.Project__c = \'' + projectId + '\'');
                }
                when 'UserId' {
                    String userId = String.escapeSingleQuotes(String.valueOf(value));
                    conditions.add('Project_Assignment__r.User__c = \'' + userId + '\'');
                }
                when 'StartDate' {
                    Date startDate = (Date) value;
                    conditions.add('Date__c >= ' + startDate);
                }
                when 'EndDate' {
                    Date endDate = (Date) value;
                    conditions.add('Date__c <= ' + endDate);
                }
            }
        }
        
        if (!conditions.isEmpty()) {
            query += ' WHERE ' + String.join(conditions, ' AND ');
        }
        
        return Database.query(query);
    }
}