force-app/main/default/objects/Project__c/fields/Total_Logged_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Logged_Hours__c</fullName>
    <label>Total Logged Hours</label>
    <summarizedField
  >Project_Assignment__c.Total_User_Logged_Hours__c</summarizedField>
    <summaryForeignKey>Project_Assignment__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/ProjectSummary.cls
public with sharing class ProjectSummary {
  public String projectName { get; private set; }
  public Decimal totalHours { get; private set; }
  public Boolean isOverBudget { get; private set; }
  
  public ProjectSummary(Project__c project) {
    this.projectName = project.Name;
    this.totalHours = project.Total_Logged_Hours__c;
    this.isOverBudget = TimeTrackerUtil.isOvertime(this.totalHours);
  }
  
}