force-app/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time_Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Log__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClientEntryTest.cls
@IsTest
public class ClientEntryTest {

    @TestSetup
    static void makeData() {
        TestDataFactory.createLogsRecords(2);
    }

    @IsTest
    static void getEntryCategoryTest() {
         ClientEntry clientEntry = getClientEntryInstance();
         Assert.areEqual('Billable', clientEntry.getEntryCategory());
    }

    @IsTest
    static void calculateTotalCostTest() {
         ClientEntry clientEntry = getClientEntryInstance();
         Assert.areEqual(4.4, clientEntry.calculateTotalCost());
    }

    private static ClientEntry getClientEntryInstance() {
        Time_Log__c log = [SELECT Id, Date__c, Duration__c, Description__c FROM Time_Log__c LIMIT 1];
        return new ClientEntry(log, 2);
    }
}