force-app/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time_Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Log__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InternalEntryTest.cls
@IsTest
public class InternalEntryTest {
    
   @TestSetup
    static void makeData() {
        TestDataFactory.createLogsRecords(2);
    }

    @IsTest
    static void getEntryCategoryTest() {
         InternalEntry internalEntry = getInternalEntryInstance();
         Assert.areEqual('Non-Billable', internalEntry.getEntryCategory());
    }

    @IsTest
    static void calculateTotalCostTest() {
         InternalEntry internalEntry = getInternalEntryInstance();
         Assert.areEqual(0, internalEntry.calculateTotalCost());
    }

    private static InternalEntry getInternalEntryInstance() {
        Time_Log__c log = [SELECT Id, Date__c, Duration__c, Description__c FROM Time_Log__c LIMIT 1];
        return new InternalEntry(log, 2);
    }
    
}