force-app/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time_Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Log__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BaseEntryType.cls
public abstract class BaseEntryType implements Comparable {
    public Time_Log__c logRecord;
    protected Decimal hourlyRate;
    
    public BaseEntryType(Time_Log__c logRecord, Decimal hourlyRate) {
        this.logRecord = logRecord;
        this.hourlyRate = hourlyRate;
    }
    
    protected abstract String getEntryCategory();
    protected virtual Decimal calculateTotalCost() {
        return logRecord.Duration__c * hourlyRate;
    }
    
    public Integer compareTo(Object obj) {
        BaseEntryType compareLogRecord = (BaseEntryType)obj;
        
        if (this.logRecord.Date__c != compareLogRecord.logRecord.Date__c) {
            return this.logRecord.Date__c > compareLogRecord.logRecord.Date__c ? 1 : -1;
        }
        if (this.logRecord.Date__c == compareLogRecord.logRecord.Date__c) {
            return this.logRecord.Duration__c > compareLogRecord.logRecord.Duration__c ? 1 : -1;
        }
        return 0;
    }
    
}